#!/usr/bin/env python
"""Run the protocol-matched E0 reference and C1-C5 baselines.

E0 makes a zero-training hard decision from compensated all-candidate EVM
scores. C1-C5 use the common pilot-compensated I/Q front-end and each paper's
native observation length through window-level prediction aggregation. The NASA
HOC baseline uses its paper-specific cumulant feature definition. Existing
completed runs are skipped and incomplete deep runs resume from ``last.pt``.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import h5py
import numpy as np
import pandas as pd
import torch

from src.utils.io import save_json


@dataclass(frozen=True)
class PaperMethod:
    method_id: str
    key: str
    display_label: str
    description: str
    model_name: str | None
    model_config: str | None
    reference: str


METHODS: dict[str, PaperMethod] = {
    "e0_nearest_evm": PaperMethod(
        "E0",
        "e0_nearest_evm",
        "E0 nearest EVM",
        "Zero-training minimum raw all-candidate EVM decision after pilot compensation",
        None,
        None,
        "Protocol-matched EVM reference",
    ),
    "c2_cnn2": PaperMethod(
        "C1",
        "c2_cnn2",
        "C1 CNN2",
        "O'Shea CNN2 on aggregated 2 x 128 I/Q windows",
        "paper_cnn2",
        "configs/model/paper_cnn2.yaml",
        "10.1007/978-3-319-44188-7_16",
    ),
    "c3_mcnet": PaperMethod(
        "C2",
        "c3_mcnet",
        "C2 MCNet",
        "Author-graph MCNet on aggregated 2 x 1024 I/Q windows",
        "paper_mcnet",
        "configs/model/paper_mcnet.yaml",
        "10.1109/LCOMM.2020.2968030",
    ),
    "c4_cnn_lstm_dual": PaperMethod(
        "C3",
        "c4_cnn_lstm_dual",
        "C3 CNN-LSTM",
        "I/Q and amplitude/phase dual-stream CNN-LSTM",
        "paper_cnn_lstm_dual",
        "configs/model/paper_cnn_lstm_dual.yaml",
        "10.1109/TVT.2020.3030018",
    ),
    "c5_satellite_cnn": PaperMethod(
        "C4",
        "c5_satellite_cnn",
        "C4 IQCNet",
        "Satellite I/Q-correlation and temporal-feature CNN",
        "paper_satellite_cnn",
        "configs/model/paper_satellite_cnn.yaml",
        "10.13700/j.bh.1001-5965.2020.0711",
    ),
    "c6_nasa_hoc_nn": PaperMethod(
        "C5",
        "c6_nasa_hoc_nn",
        "C5 NASA HOC-NN",
        "NASA 10-40-40-40-7 network on symbol cumulants and pilot Es/N0",
        "paper_nasa_hoc_nn",
        "configs/model/paper_nasa_hoc_nn.yaml",
        "NASA NTRS 20170006541",
    ),
}


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Run the E0 and C1-C5 paper-baseline comparison.")
    p.add_argument("--raw-data", default="data/processed/leo_7mods_snr_balanced_trainval_pilot.h5")
    p.add_argument(
        "--feature-data",
        default="data/features/leo_7mods_snr_balanced_trainval_hoc_iqcomp_coherent.h5",
    )
    p.add_argument(
        "--paper-feature-data",
        default="data/features/leo_7mods_snr_balanced_trainval_paper_baselines_coherent.h5",
        help="NASA-HOC paper-specific feature file generated by the features stage.",
    )
    p.add_argument("--splits", default="data/splits/leo_7mods_snr_balanced_trainval_pilot_splits.npz")
    p.add_argument("--train-config", default="configs/train/train_long.yaml")
    p.add_argument("--checkpoint-root", default="outputs/checkpoints/paper_baselines_faithful_coherent")
    p.add_argument("--result-root", default="outputs/results/paper_baselines_faithful_coherent")
    p.add_argument(
        "--summary-output",
        default="outputs/results/paper_baselines_faithful_coherent/summary.csv",
    )
    p.add_argument("--figure-root", default="outputs/figures/paper")
    p.add_argument(
        "--proposed-checkpoint",
        default="outputs/checkpoints/exact_mixture/protocol_a/proposed/seed_41/best.pt",
    )
    p.add_argument(
        "--proposed-eval-csv",
        default="outputs/results/paper_baselines_faithful_coherent/proposed_exact_mixture_val.csv",
    )
    p.add_argument(
        "--proposed-model-config",
        default="configs/model/triplenet_iq_evm.yaml",
    )
    p.add_argument(
        "--symbol-feature-data",
        default="data/features/exact_mixture/protocol_a_trainval_symbol_exact.h5",
        help="Needed only if the proposed compact-main evaluation CSV must be regenerated.",
    )
    p.add_argument(
        "--methods",
        nargs="+",
        default=list(METHODS),
        choices=list(METHODS),
    )
    p.add_argument(
        "--stages",
        nargs="+",
        default=["features", "train", "eval", "summary", "plots"],
        choices=["features", "train", "eval", "summary", "plots"],
    )
    p.add_argument("--eval-split", default="val", choices=["train", "val", "test"])
    p.add_argument("--device", default="cuda")
    p.add_argument("--batch-size-eval", type=int, default=256)
    p.add_argument("--num-workers-eval", type=int, default=4)
    p.add_argument("--no-proposed", action="store_true")
    p.add_argument("--overwrite", action="store_true")
    p.add_argument("--dry-run", action="store_true")
    return p.parse_args()


def _script(name: str) -> str:
    return str(PROJECT_ROOT / "scripts" / name)


def _run(cmd: list[str], dry_run: bool) -> None:
    printable = " ".join(f'"{x}"' if " " in str(x) else str(x) for x in cmd)
    print(f"\n$ {printable}")
    if not dry_run:
        subprocess.run(cmd, check=True)


def _checkpoint_dir(args: argparse.Namespace, key: str) -> Path:
    return Path(args.checkpoint_root) / key


def _eval_csv(args: argparse.Namespace, key: str) -> Path:
    return Path(args.result_root) / f"{key}_{args.eval_split}.csv"


def _eval_summary(args: argparse.Namespace, key: str) -> Path:
    return Path(args.result_root) / f"{key}_{args.eval_split}.summary.json"


def _validate_inputs(args: argparse.Namespace) -> None:
    paths = {
        "raw_data": args.raw_data,
        "feature_data": args.feature_data,
        "splits": args.splits,
        "train_config": args.train_config,
    }
    if "features" in args.stages or "e0_nearest_evm" in args.methods:
        paths["symbol_feature_data"] = args.symbol_feature_data
    elif "c6_nasa_hoc_nn" in args.methods:
        paths["paper_feature_data"] = args.paper_feature_data
    for key in args.methods:
        cfg = METHODS[key].model_config
        if cfg is not None:
            paths[f"model_config[{key}]"] = cfg
    if not args.no_proposed and not Path(args.proposed_eval_csv).exists():
        paths["proposed_checkpoint"] = args.proposed_checkpoint
        paths["proposed_model_config"] = args.proposed_model_config
        paths["symbol_feature_data"] = args.symbol_feature_data
    missing = [f"{name}: {path}" for name, path in paths.items() if not Path(path).exists()]
    if missing:
        raise SystemExit("Missing required input(s):\n" + "\n".join(missing))


def _precompute_paper_features(args: argparse.Namespace) -> None:
    cmd = [
        sys.executable,
        _script("11_precompute_paper_baseline_features.py"),
        "--raw-data",
        args.raw_data,
        "--comp-feature-data",
        args.feature_data,
        "--symbol-feature-data",
        args.symbol_feature_data,
        "--output",
        args.paper_feature_data,
    ]
    if args.overwrite:
        cmd.append("--overwrite")
    _run(cmd, args.dry_run)


def _train_deep(args: argparse.Namespace, method: PaperMethod) -> None:
    if method.model_name is None:
        print(f"No training required: {method.display_label}")
        return
    out_dir = _checkpoint_dir(args, method.key)
    completed = out_dir / "train_result.json"
    if completed.exists() and (out_dir / "best.pt").exists() and not args.overwrite:
        print(f"Skip existing: {completed}")
        return
    feature_data = (
        args.paper_feature_data
        if method.key == "c6_nasa_hoc_nn"
        else args.feature_data
    )
    iq_source = "raw" if method.key == "c6_nasa_hoc_nn" else "comp"
    iq_normalize = "power" if method.key == "c4_cnn_lstm_dual" else "zscore"
    hoc_transform = "none" if method.key == "c6_nasa_hoc_nn" else "signed_log1p"
    cmd = [
        sys.executable,
        _script("13_train_model.py"),
        "--raw-data",
        args.raw_data,
        "--feature-data",
        feature_data,
        "--splits",
        args.splits,
        "--model",
        str(method.model_name),
        "--model-config",
        str(method.model_config),
        "--train-config",
        args.train_config,
        "--output-dir",
        str(out_dir),
        "--device",
        args.device,
        "--num-workers",
        "0",
        "--iq-source",
        iq_source,
        "--iq-normalize",
        iq_normalize,
        "--hoc-transform",
        hoc_transform,
    ]
    if method.key != "c6_nasa_hoc_nn":
        cmd.append("--cache-iq")
    if method.key != "c6_nasa_hoc_nn":
        cmd.extend(["--no-hoc-standardize"])
    last = out_dir / "last.pt"
    if last.exists() and not completed.exists() and not args.overwrite:
        cmd.extend(["--resume", str(last)])
    _run(cmd, args.dry_run)


def _evaluate_nearest_evm(
    args: argparse.Namespace,
    method: PaperMethod,
    output: Path,
    summary: Path,
) -> None:
    """Evaluate the protocol-matched, zero-training minimum-EVM reference.

    This is not labelled as a faithful reproduction of an external EVM-AMC
    implementation. It evaluates the direct decision rule available from this
    receiver's compensated all-candidate EVM scores.
    """

    with np.load(args.splits) as split_file:
        if args.eval_split not in split_file:
            raise KeyError(f"Split {args.eval_split!r} is missing from {args.splits}")
        indices = np.asarray(split_file[args.eval_split], dtype=np.int64)

    with h5py.File(args.symbol_feature_data, "r") as feature_file:
        required = {"all_candidate_evm", "label", "snr_db", "symbol_valid"}
        missing = sorted(required.difference(feature_file.keys()))
        if missing:
            raise KeyError(
                "Symbol feature data is missing required EVM-reference datasets: "
                f"{missing}"
            )
        scores = np.asarray(feature_file["all_candidate_evm"][indices], dtype=np.float64)
        labels = np.asarray(feature_file["label"][indices], dtype=np.int64)
        snr_db = np.asarray(feature_file["snr_db"][indices], dtype=np.float64)
        valid = np.asarray(feature_file["symbol_valid"][indices], dtype=bool)

    pred = np.argmin(np.where(np.isfinite(scores), scores, np.inf), axis=1).astype(np.int64)
    correct = valid & (pred == labels)
    frame = pd.DataFrame(
        {
            "index": indices,
            "label": labels,
            "pred": pred,
            "correct": correct.astype(np.int8),
            "snr_db": snr_db,
            "symbol_valid": valid,
        }
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    frame.to_csv(output, index=False)
    save_json(
        {
            "method": method.key,
            "display_label": method.display_label,
            "decision_rule": "argmin_m all_candidate_evm[m]",
            "score_type": "raw EVM without order or APSK penalties",
            "protocol_note": (
                "Protocol-matched zero-training reference; not a faithful reproduction "
                "of an external EVM-AMC implementation."
            ),
            "num_samples": int(len(frame)),
            "valid_fraction": float(np.mean(valid)) if len(valid) else float("nan"),
            "accuracy": float(np.mean(correct)) if len(correct) else float("nan"),
        },
        summary,
    )
    print(f"Saved EVM hard-decision evaluation: {output}")


def _evaluate_deep(args: argparse.Namespace, method: PaperMethod) -> None:
    output = _eval_csv(args, method.key)
    summary = _eval_summary(args, method.key)
    if output.exists() and summary.exists() and not args.overwrite:
        print(f"Skip existing: {output}")
        return
    if method.model_name is None:
        _evaluate_nearest_evm(args, method, output, summary)
        return
    feature_data = (
        args.paper_feature_data
        if method.key == "c6_nasa_hoc_nn"
        else args.feature_data
    )
    cmd = [
        sys.executable,
        _script("14_evaluate_model.py"),
        "--checkpoint",
        str(_checkpoint_dir(args, method.key) / "best.pt"),
        "--raw-data",
        args.raw_data,
        "--feature-data",
        feature_data,
        "--splits",
        args.splits,
        "--split",
        args.eval_split,
        "--model",
        str(method.model_name),
        "--model-config",
        str(method.model_config),
        "--output",
        str(output),
        "--summary-output",
        str(summary),
        "--batch-size",
        str(args.batch_size_eval),
        "--num-workers",
        "0",
        "--device",
        args.device,
        "--no-aux",
    ]
    if method.key != "c6_nasa_hoc_nn":
        cmd.append("--cache-iq")
    _run(cmd, args.dry_run)


def _evaluate_proposed(args: argparse.Namespace) -> None:
    if args.no_proposed or Path(args.proposed_eval_csv).exists():
        return
    output = Path(args.proposed_eval_csv)
    cmd = [
        sys.executable,
        _script("14_evaluate_model.py"),
        "--checkpoint",
        args.proposed_checkpoint,
        "--raw-data",
        args.raw_data,
        "--feature-data",
        args.feature_data,
        "--symbol-feature-data",
        args.symbol_feature_data,
        "--splits",
        args.splits,
        "--split",
        args.eval_split,
        "--model",
        "drc_triplenet",
        "--model-config",
        args.proposed_model_config,
        "--output",
        str(output),
        "--batch-size",
        str(args.batch_size_eval),
        "--num-workers",
        str(args.num_workers_eval),
        "--device",
        args.device,
        "--no-aux",
    ]
    _run(cmd, args.dry_run)


def _torch_parameter_count(path: Path) -> int:
    checkpoint = torch.load(path, map_location="cpu", weights_only=False)
    state = checkpoint.get("model_state_dict", checkpoint)
    buffer_suffixes = ("running_mean", "running_var", "num_batches_tracked")
    return int(
        sum(
            value.numel()
            for key, value in state.items()
            if torch.is_tensor(value) and not key.endswith(buffer_suffixes)
        )
    )


def _summarize(args: argparse.Namespace) -> None:
    if args.dry_run:
        print(f"Dry-run: summary would be saved to {args.summary_output}")
        return
    rows: list[dict[str, object]] = []
    for key in args.methods:
        method = METHODS[key]
        eval_csv = _eval_csv(args, key)
        if not eval_csv.exists():
            raise FileNotFoundError(f"Missing evaluation result: {eval_csv}")
        df = pd.read_csv(eval_csv, usecols=["correct"])
        checkpoint_path = _checkpoint_dir(args, key) / "best.pt" if method.model_name else None
        parameters = _torch_parameter_count(checkpoint_path) if checkpoint_path is not None else np.nan
        support_vectors = np.nan
        checkpoint = str(checkpoint_path) if checkpoint_path is not None else "N/A"
        rows.append(
            {
                "method_id": method.method_id,
                "method": key,
                "display_label": method.display_label,
                "description": method.description,
                "accuracy": float(df["correct"].mean()),
                "num_samples": int(len(df)),
                "parameter_count": parameters,
                "support_vector_count": support_vectors,
                "checkpoint": checkpoint,
                "eval_csv": str(eval_csv),
                "reference": method.reference,
            }
        )

    if not args.no_proposed:
        proposed_csv = Path(args.proposed_eval_csv)
        if not proposed_csv.exists():
            raise FileNotFoundError(f"Missing proposed-model evaluation: {proposed_csv}")
        df = pd.read_csv(proposed_csv, usecols=["correct"])
        rows.append(
            {
                "method_id": "Proposed",
                "method": "proposed",
                "display_label": "Proposed I/Q+EVM",
                "description": "Compact pilot-compensated I/Q+EVM model",
                "accuracy": float(df["correct"].mean()),
                "num_samples": int(len(df)),
                "parameter_count": _torch_parameter_count(Path(args.proposed_checkpoint)),
                "support_vector_count": np.nan,
                "checkpoint": args.proposed_checkpoint,
                "eval_csv": str(proposed_csv),
                "reference": "This work",
            }
        )

    summary = pd.DataFrame(rows)
    print("\nPaper baseline comparison")
    print(summary[["method_id", "display_label", "accuracy", "parameter_count"]].to_string(index=False))
    output = Path(args.summary_output)
    output.parent.mkdir(parents=True, exist_ok=True)
    summary.to_csv(output, index=False)
    save_json(
        {
            "summary_csv": str(output),
            "raw_data": args.raw_data,
            "feature_data": args.feature_data,
            "paper_feature_data": args.paper_feature_data,
            "splits": args.splits,
            "eval_split": args.eval_split,
            "input_policy": (
                "E0 uses the minimum raw all-candidate EVM score after pilot compensation; "
                "C1-C4 use pilot-compensated IQ; C5 uses nine symbol cumulants plus "
                "pilot-EVM Es/N0 estimate."
            ),
            "adaptation_policy": (
                "Long frames are divided into each paper's native window "
                "length and window logits are averaged. Output width is seven."
            ),
            "strict_same_input_experiment": False,
        },
        output.with_suffix(".json"),
    )
    print(f"Saved: {output}")


def _plot(args: argparse.Namespace) -> None:
    cmd = [
        sys.executable,
        _script("46_plot_paper_baseline_comparison.py"),
        "--summary",
        args.summary_output,
        "--output-dir",
        args.figure_root,
        "--table-output",
        str(Path(args.result_root) / "snr_curve.csv"),
        "--accuracy-output",
        "paper_baseline_coherent_accuracy_vs_snr.pdf",
        "--overall-output",
        "paper_baseline_coherent_overall_accuracy.pdf",
    ]
    _run(cmd, args.dry_run)


def main() -> None:
    args = parse_args()
    _validate_inputs(args)
    Path(args.checkpoint_root).mkdir(parents=True, exist_ok=True)
    Path(args.result_root).mkdir(parents=True, exist_ok=True)

    if "features" in args.stages:
        _precompute_paper_features(args)

    for key in args.methods:
        method = METHODS[key]
        print(f"\n=== {method.method_id}: {method.display_label} ===")
        if "train" in args.stages:
            _train_deep(args, method)
        if "eval" in args.stages:
            _evaluate_deep(args, method)

    if "eval" in args.stages:
        _evaluate_proposed(args)
    if "summary" in args.stages:
        _summarize(args)
    if "plots" in args.stages:
        if not Path(args.summary_output).exists() and not args.dry_run:
            raise FileNotFoundError("Run the summary stage before plots.")
        _plot(args)


if __name__ == "__main__":
    main()
